Repository jessesquires/ReactiveCollectionsKit, pull requests merged in 2024-10, with the labels that each got.

#116 Update to Xcode 16 + address Swift concurrency issues
  .github/workflows/ci.yml
  .github/workflows/spm-ios.yml
  CHANGELOG.md
  Example/ExampleApp.xcodeproj/project.pbxproj
  Example/ExampleApp.xcodeproj/xcshareddata/xcschemes/ExampleApp.xcscheme
  Example/Sources/Grid/GridPersonCell.swift
  Example/Tests/UITests/GridUITests.swift
  Example/Tests/UITests/ListUITests.swift
  Package.swift
  README.md
  ReactiveCollectionsKit.xcodeproj/project.pbxproj
  ReactiveCollectionsKit.xcodeproj/xcshareddata/xcschemes/ReactiveCollectionsKit.xcscheme
  Sources/DiffableDataSource.swift
  Tests/TestCellEventCoordinator.swift
  Tests/TestCollectionViewDriver.swift
  Tests/TestCollectionViewDriverReconfigure.swift
  Tests/TestDiffableSnapshot.swift
  Tests/TestEmptyView.swift
  Tests/Utils/UnitTestCase.swift
Labels: enhancement

#127 Implement additional Single Selection APIs
  CHANGELOG.md
  Example/Sources/Grid/GridViewController.swift
  Example/Sources/Grid/PersonCellViewModelGrid.swift
  Sources/CellEventCoordinator.swift
  Sources/CellViewModel.swift
  Sources/CollectionViewDriver.swift
  Tests/Fakes/FakeCellEventCoordinator.swift
  Tests/Fakes/FakeCellNibView.swift
  Tests/Fakes/FakeCollectionViewModel.swift
  Tests/Fakes/FakeNumberModel.swift
  Tests/Fakes/FakeTextModel.swift
  Tests/TestCellEventCoordinator.swift
  Tests/TestCellViewModel.swift
  Tests/TestCollectionViewDriver.swift
  Tests/Utils/TestExpectationField.swift
Labels: enhancement, feature request

#133 Exposes `UIScrollViewDelegate` to clients
  CHANGELOG.md
  Example/Sources/List/ListViewController.swift
  Sources/CollectionViewDriver.swift
Labels: feature request

#134 Allow setting a `UICollectionViewDelegateFlowLayout`
  CHANGELOG.md
  Example/Sources/FlowLayout/SimpleFlowLayoutViewController.swift
  Sources/CollectionViewDriver.swift
  Tests/Fakes/FakeFlowLayoutDelegate.swift
  Tests/TestFlowLayoutDelegate.swift
  Tests/TestScrollViewDelegate.swift
  Tests/Utils/UnitTestCase.swift
Labels: enhancement, feature request

#135 [Perf] Redesign MainActor isolation + loosen requirements
  CHANGELOG.md
  Example/ExampleApp.xcodeproj/project.pbxproj
  Example/Sources/FlowLayout/SimpleFlowLayoutViewController.swift
  Example/Sources/Grid/ColorCellViewModelGrid.swift
  Example/Sources/Grid/PersonCellViewModelGrid.swift
  Example/Sources/List/ColorCellViewModelList.swift
  Example/Sources/List/PersonCellViewModelList.swift
  Example/Sources/SimpleStatic/SimpleStaticViewController.swift
  Example/Sources/SupplementaryViews/FooterView.swift
  Example/Sources/SupplementaryViews/HeaderView.swift
  Example/Tests/UITests/StaticViewUITests.swift
  Sources/CellViewModel.swift
  Sources/CollectionViewConstants.swift
  Sources/CollectionViewModel.swift
  Sources/DebugDescriptions.swift
  Sources/DiffableViewModel.swift
  Sources/SectionViewModel.swift
  Sources/SupplementaryFooterViewModel.swift
  Sources/SupplementaryHeaderViewModel.swift
  Sources/SupplementaryViewModel.swift
  Sources/ViewRegistration.swift
  Sources/ViewRegistrationProvider.swift
  Sources/ViewRegistrationViewType.swift
  Tests/Fakes/FakeCellNibView.swift
  Tests/Fakes/FakeNumberModel.swift
  Tests/Fakes/FakeSupplementaryNibView.swift
  Tests/Fakes/FakeSupplementaryViewModel.swift
  Tests/Fakes/FakeTextModel.swift
  Tests/TestCollectionExtensions.swift
  Tests/TestCollectionViewConstants.swift
  Tests/TestCollectionViewDriverReconfigure.swift
  Tests/TestViewRegistrationViewType.swift
Labels: enhancement

#136 [Perf] avoid unnecessary copies of cells
  CHANGELOG.md
  Sources/CollectionViewModel.swift
  Sources/DiffableSnapshot.swift
Labels: enhancement

#138 Fix perf regression in DiffableSnapshot init
  CHANGELOG.md
  Sources/DiffableSnapshot.swift
  Tests/Fakes/FakeCollectionViewModel.swift
  Tests/TestDiffableSnapshot.swift
Labels: bug, performance

#137 [Perf] Do more diffing work on a background queue
  CHANGELOG.md
  Sources/CellViewModel.swift
  Sources/DiffableDataSource.swift
  Sources/DiffableViewModel.swift
  Sources/SupplementaryViewModel.swift
Labels: enhancement, performance

#139 Implement CustomDebugStringConvertible for CollectionViewDriver and CollectionViewDriverOptions
  CHANGELOG.md
  Sources/CollectionViewDriver.swift
  Sources/CollectionViewDriverOptions.swift
  Sources/DebugDescriptions.swift
  Tests/TestCollectionViewDriverOptions.swift
  Tests/TestDebugDescriptionDriver.swift
Labels: enhancement
